language: node_js
node_js: "8"

before_script:
  - npm run eslint

before_deploy:
  - node pack.js
  - cd dist

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true